Barriers config=config.ini genome_length=1 chain=0 outdir=l1c0_rep1
Barriers config=config.ini genome_length=2 chain=0 outdir=l2c0_rep1
Barriers config=config.ini genome_length=4 chain=0 outdir=l4c0_rep1
Barriers config=config.ini genome_length=8 chain=0 outdir=l8c0_rep1
Barriers config=config.ini genome_length=16 chain=0 outdir=l16c0_rep1
Barriers config=config.ini genome_length=1 chain=1 outdir=l1c1_rep1
Barriers config=config.ini genome_length=2 chain=1 outdir=l2c1_rep1
Barriers config=config.ini genome_length=4 chain=1 outdir=l4c1_rep1
Barriers config=config.ini genome_length=8 chain=1 outdir=l8c1_rep1
Barriers config=config.ini genome_length=16 chain=1 outdir=l16c1_rep1

Barriers config=config.ini genome_length=1 chain=0 outdir=l1c0_rep2
Barriers config=config.ini genome_length=2 chain=0 outdir=l2c0_rep2
Barriers config=config.ini genome_length=4 chain=0 outdir=l4c0_rep2
Barriers config=config.ini genome_length=8 chain=0 outdir=l8c0_rep2
Barriers config=config.ini genome_length=16 chain=0 outdir=l16c0_rep2
Barriers config=config.ini genome_length=1 chain=1 outdir=l1c1_rep2
Barriers config=config.ini genome_length=2 chain=1 outdir=l2c1_rep2
Barriers config=config.ini genome_length=4 chain=1 outdir=l4c1_rep2
Barriers config=config.ini genome_length=8 chain=1 outdir=l8c1_rep2
Barriers config=config.ini genome_length=16 chain=1 outdir=l16c1_rep2

Barriers config=config.ini genome_length=1 chain=0 outdir=l1c0_rep3
Barriers config=config.ini genome_length=2 chain=0 outdir=l2c0_rep3
Barriers config=config.ini genome_length=4 chain=0 outdir=l4c0_rep3
Barriers config=config.ini genome_length=8 chain=0 outdir=l8c0_rep3
Barriers config=config.ini genome_length=16 chain=0 outdir=l16c0_rep3
Barriers config=config.ini genome_length=1 chain=1 outdir=l1c1_rep3
Barriers config=config.ini genome_length=2 chain=1 outdir=l2c1_rep3
Barriers config=config.ini genome_length=4 chain=1 outdir=l4c1_rep3
Barriers config=config.ini genome_length=8 chain=1 outdir=l8c1_rep3
Barriers config=config.ini genome_length=16 chain=1 outdir=l16c1_rep3